name: CI for Cassandra Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:4.0
        

        ports:
          - 9042:9042
        options: >-
          --name cassandra_test
          --health-cmd "cqlsh -e 'DESCRIBE KEYSPACES'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Cassandra to be fully ready
        run: |
          for i in {1..30}; do
            if docker exec cassandra_test  cqlsh -e "DESCRIBE KEYSPACES"; then
              echo "Cassandra is fully ready!"
              break
            fi
            echo "Waiting for Cassandra..."
            sleep 5
          done

      - name: Apply company.cql via echo
        run: |
          docker exec cassandra_test  cqlsh -e "$(cat company.cql)"

      - name: Verify keyspace 'company' exists
        run: |
          for i in {1..10}; do
            if docker exec cassandra_test  cqlsh -e "DESCRIBE KEYSPACES" | grep -q company; then
              echo "Keyspace 'company' is ready!"
              break
            fi
            echo "Waiting for keyspace 'company'..."
            sleep 5
          done

      - name: Apply other CQL scripts
        run: |
          for file in $(find . -name '*.cql' | grep -v 'company.cql'); do
            echo "Applying $file..."
            docker cp "$file" cassandra_test :/"$(basename $file)"
            docker exec cassandra_test  cqlsh -f "/$(basename $file)" || (echo "Failed to apply $file!" && exit 1)
          done


      - name: List all CQL files
        run: ls -l *.cql
      
      - name: List keyspaces after execution
        run: docker exec cassandra_test  cqlsh -e "DESCRIBE KEYSPACES"
      - name: Show company.cql content before copying
        run: cat company.cql


      - name: Check if table exists
        run: docker exec cassandra_test cqlsh -e "SELECT table_name FROM system_schema.tables WHERE keyspace_name = 'company';"



      - name: Apply vstavka.cql
        run: |
         docker exec cassandra_test cqlsh -f /vstavka.cql || (echo "Failed to apply vstavka.cql!" && exit 1)

      #- name: Insert test data
        #run: |
          #docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "INSERT INTO test_keyspace.users (id, name) VALUES (1, 'Ekaterina');"


      - name: Fetch all employees
        run: |
          echo "Fetching all employees..."
          docker exec cassandra_test  cqlsh -e "SELECT * FROM company.employees;"

      - name: Fetch employees with salary > 50000
        run: |
          echo "Fetching employees with salary > 50000..."
          docker exec cassandra_test  cqlsh -e "SELECT * FROM company.employees WHERE salary > 50000.00 ALLOW FILTERING;"


      



