name: CI for Cassandra Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:4.0
        container_name: cassandra
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'DESCRIBE KEYSPACES'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Cassandra to be ready
        run: |
          for i in {1..30}; do
            if docker exec cassandra cqlsh -e "DESCRIBE KEYSPACES"; then
              echo "Cassandra is ready!"
              break
            fi
            echo "Waiting for Cassandra..."
            sleep 5
          done

      - name: Copy schema to container
        run: docker cp schema.cql cassandra:/schema.cql

      - name: Apply schema
        run: |
          echo "Applying schema..."
          docker exec cassandra cqlsh -f /schema.cql || (echo "Schema failed to apply!" && exit 1)
          echo "Schema applied successfully!"
          sleep 5

      - name: Check if keyspace exists
        run: docker exec cassandra cqlsh -e "DESCRIBE KEYSPACES"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest test.py
