name: CI for Cassandra Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:4.0
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'DESCRIBE KEYSPACES'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Cassandra to be ready
        run: |
          for i in {1..30}; do
            if docker run --network=host --rm cassandra:4.0 cqlsh -e "DESCRIBE KEYSPACES"; then
              echo "Cassandra is ready!"
              break
            fi
            echo "Waiting for Cassandra..."
            sleep 5
          done

      - name: Apply all CQL scripts
        run: |
          for file in $(find . -name '*.cql'); do
              echo "Applying $file..."
              docker cp "$file" $(docker ps -q -f ancestor=cassandra:4.0):/"$(basename $file)"
              docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -f "/$(basename $file)" || (echo "Failed to apply $file!" && exit 1)
          done
      - name: Wait for keyspace creation
        run: sleep 5

      - name: Verify keyspace and table
        run: |
          echo "Checking if keyspace 'company' exists..."
          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES" | grep -q company || (echo "Keyspace 'company' not found!" && exit 1)
          
          echo "Checking if table 'employees' exists..."
          docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE TABLES IN company" | grep -q employees || (echo "Table 'employees' not found!" && exit 1)



     
      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Insert test data
        #run: |
          #docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "INSERT INTO test_keyspace.users (id, name) VALUES (1, 'Ekaterina');"

      #- name: Fetch data from Cassandra
      #  run: |
      #    docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "SELECT * FROM test_keyspace.users;"
