name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:4.0
        ports:
          - 9042:9042

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Устанавливаем зависимости
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install cassandra-driver pytest

      - name: Ожидаем запуск Cassandra
        run: |
          for i in {1..30}; do
            if docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES"; then
              echo "Cassandra is ready!"
              exit 0
            fi
            echo "Waiting for Cassandra..."
            sleep 5
          done
          echo "Cassandra did not start in time!"
          exit 1

      - name: Копируем файлы внутрь контейнера
        run: |
          CONTAINER_ID=$(docker ps -q -f ancestor=cassandra:4.0)
          docker cp schema.cql $CONTAINER_ID:/schema.cql
          docker cp test.py $CONTAINER_ID:/test.py  # Копируем test.py

      - name: Проверяем, загружены ли файлы в контейнер
        run: |
          CONTAINER_ID=$(docker ps -q -f ancestor=cassandra:4.0)
          docker exec $CONTAINER_ID ls -lah /

      - name: Ждем 10 секунд перед выполнением schema.cql
        run: sleep 10

      - name: Применяем schema.cql
        run: docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -f /schema.cql

      - name: Проверяем, загружен ли my_keyspace
        run: docker exec $(docker ps -q -f ancestor=cassandra:4.0) cqlsh -e "DESCRIBE KEYSPACES"

      - name: Запускаем тесты
        run: pytest test.py
